### ISSUE TITLE
SNES (Beetle bSNES): Error opening save file

### ISSUE THREAD

**Issue by Neverest** [kodi-game/game.libretro.beetle-bsnes#1]
When selecting the game it says "Error opening selected game.sfc/smc". Was pointed out that the core was failing because it says the save file doesn't exist, but in these games that I tried they have a save file available. 

http://paste.ubuntu.com/12637401/

**Comment by garbear** [comment]
The problem may be that the save directory doesn't exist:

```
ERROR: XFILE::CDirectory::Create - Error creating C:\Users\Heat\AppData\Roaming\Kodi\userdata\addon_data\game.libretro.beetle-bsnes\system
ERROR: XFILE::CDirectory::Create - Error creating C:\Users\Heat\AppData\Roaming\Kodi\userdata\addon_data\game.libretro.beetle-bsnes\save
```

This was fixed in https://github.com/garbear/xbmc/commit/0891907 and should have been included in the 2015-10-01 build

**Comment by garbear** [comment]
ofc, it could also be a problem with beetle bsnes

**Comment by Neverest** [comment]
Tried it with the 10-01 build, still get that error. Noticed that the beetle emulators are giving this error opening file problems.

http://paste.ubuntu.com/12644494/

**Comment by garbear** [comment]
Is this still an issue?
